### ISSUE TITLE
Notification link in mail are broken

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#111]
Hi ;)
notification mail are bugged (perhaps only on my server ?) 
the link is https://mat.krashboyz.org/krashboyz/krashboyz/pl/<blahblahblah>
i think it should be https://mat.krashboyz.org/krashboyz/pl/<blahblahblah>

How/Where can i modify it please ?

mattermost version: 4.6.0-1

Thx for your (dayly) Help :D

**Comment by kemenaran** [comment]
Hmm, good question. I'm not sure about this, but did you have a look at the [SiteURL](https://docs.mattermost.com/administration/config-settings.html#site-url) configuration variable? Does it match your server setup?

You should be able to see and edit the variable from the Mattermost client, by going to `System Console ▸ Settings ▸ General ▸ Configuration`.

**Comment by isAAAc** [comment]
yes mea culpa, i added <based_url>/krashboyz , 
it works better after deleted /krashboyz 
sorry for the misconfiguration on by my side, 
and thx for your help ;)

**Comment by kemenaran** [comment]
You're welcome!
