### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by vibhi19** [YunoHost-Apps/mattermost_ynh#135]
There are multiple types of encryption with Mattermost

1.TLS 
https://docs.mattermost.com/install/config-tls-mattermost.html
2.Encryption options at the disk level are documented both for MySQL and PostgreSQL.
https://www.postgresql.org/docs/8.1/encryption-options.html
3. Minio ( basically storage server)
4. encryption-at-rest is available for files stored via hardware and software disk encryption solutions applied to the server

So 1 and 2 or implemented by default or not? and if not how can i set them up while using yunohost
and if you can provide some info about 4 that would be cool

**Comment by kemenaran** [comment]
Type 1. (TLS) is already implemented by the Yunohost layer : data transiting from web browsers and apps to the Mattermost instance are encrypted as long as you use an HTTPS url (which is enabled by default on Yunohost).

Type 2. (database encryption) could be implemented automatically, but as the database is shared system-wide it has to be done by Yunohost itself.

Encryption-of-disk-at-rest can also be implemented by Yunohost, but it is a responsability of the system, not of Mattermost.

**Comment by vibhi19** [comment]
> Type 1. (TLS) is already implemented by the Yunohost layer : data transiting from web browsers and apps to the Mattermost instance are encrypted as long as you use an HTTPS url (which is enabled by default on Yunohost).

Good 

> 
> Type 2. (database encryption) could be implemented automatically, but as the database is shared system-wide it has to be done by Yunohost itself.
> 
So You have to implement it or I have to do it via Yunohost admin panel. If yes do tell me how.

> Encryption-of-disk-at-rest can also be implemented by Yunohost, but it is a responsability of the system, not of Mattermost.

Again how? if you can tell me please

**Comment by vibhi19** [comment]
Sorry for asking  too many question but i really need help regarding this does yunohost forum can help?

**Comment by vibhi19** [comment]
They have given a dedicated setting for TLS in mattermost application so it make sense to setup there or there is no need to do that as it handle by yunohost itself?

other question  are solved so i deleted them.

https://docs.mattermost.com/install/config-tls-mattermost.html

**Comment by kemenaran** [comment]
Yes, the TLS connection is handled by Yunohost ; no need to enable it in Mattermost itself

**Comment by vibhi19** [comment]
> Yes, the TLS connection is handled by Yunohost ; no need to enable it in Mattermost itself

Thanks i already figure out the storage encryption although can you point out where should i look database encryption?
