### ISSUE TITLE
Editing Config.json

### ISSUE THREAD

**Issue by vibhi19** [YunoHost-Apps/mattermost_ynh#136]
I wanted to edit config.json to enable Plugin Feature but its not in Opt/mattermost folder.

Can you tell me where the file is?

**Comment by kemenaran** [comment]
Sure – it should be in `/var/www/mattermost/config.json`.

**Comment by vibhi19** [comment]
> /var/www/mattermost/config.json

its in //var/www/mattermost/config/config.json
