### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/mattermost_ynh#15]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by kemenaran** [comment]
@frju365 sure ; just done.

**Comment by kemenaran** [comment]
@frju365 now if you could add me to one of the Yunohost-Apps teams, so I can get commit rights on this repository again :)

**Comment by frju365** [comment]
You have already this right. :)
