### ISSUE TITLE
Can't send email notification 

### ISSUE THREAD

**Issue by arnaudbagnis** [YunoHost-Apps/mattermost_ynh#156]
> configuration : 
> yunohost : 3.6.5.3
> mattermost : 4.6.0-1

Hello,
I cannot correct the problem of sending mail.
- Forgotten password notification
- Notification with each message
I tried to go to the smtp configuration. 

>web console application link  /admin_console/environment/smtp

But it shows me a sendmail error : 

`Une erreur s'est produite lors de la connexion : La connexion n'a pas pu être établie : SendMail: Failed to open connection, dial tcp [::1]:10025: connect: connection refused - undefined
`

the mail configuration works very well, it has been tested elsewhere.

**Comment by kemenaran** [comment]
@arnaudbagnis mmm, good question.

I imagine it could be a firewall issue. The mattermost server runs under the user `mattermost` ; maybe this system user doesn't have access to your SMTP port?

**Comment by Jaxom99** [comment]
I encountered the same trouble on a fresh install. Turns out the configured SMTP port (10025) is wrong :/ On Ynh, port 25 is used, and it works for localhost connections.

@arnaudbagnis you can solve your trouble by setting the port to 25 and leaving the rest of SMTP setup unchanged.

@kemenaran I don't get why this port is set. Do you have time to look into it ? I may share logs...

**Comment by arnaudbagnis** [comment]
Hello, 
I solved my problem !
 - I **changed** the configuration in **web app console** 
- I **saved** despite the error.
- then I **refresh the page** and came back testing and this to work

I hope it worked for you...

**Comment by Jaxom99** [comment]
Yes indded ! I did the same (setting to port 25) and it worked right away, no error displayed, and a test mail in my (ynh) inbox.

We just have to change it in the install script then ;)

**Comment by arnaudbagnis** [comment]
> Yes indded ! I did the same (setting to port 25) and it worked right away, no error displayed, and a test mail in my (ynh) inbox.
> 
> We just have to change it in the install script then ;)

Did you succeed thanks to me or did you offer me the same solution that I found?  

Sorry, I have a little problems with understanding despite the quality of today's translators XD

**Comment by kemenaran** [comment]
I just tested on my own development environment, and indeed the default Mattermost port wasn't replaced by the 25 port suitable for Yunohost (although the install script was requesting it).

I fixed the script in #161 ; it should be fixed on master now.

Sorry for the inconvenience, and thanks to you all for the bug reports!
