### ISSUE TITLE
Can't install mattermost twice

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/mattermost_ynh#163]
see https://forum.yunohost.org/t/second-instance-of-mattermost/10311

**Comment by kemenaran** [comment]
Thanks for the heads up!

I just pushed a fix for multi-instances to the `testing` branch. You should be able to install several different versions of Mattermost on different instances using the testing branch:

shell
```
sudo yunohost app install https://github.com/YunoHost-Apps/mattermost_ynh/tree/testing/
```

Could you tell me if this works?

**Comment by liebeimquadrat** [comment]
> Thanks for the heads up!
> 
> I just pushed a fix for multi-instances to the `testing` branch. You should be able to install several different versions of Mattermost on different instances using the testing branch:
> 
> shell
> 
> ```
> sudo yunohost app install https://github.com/YunoHost-Apps/mattermost_ynh/tree/testing/
> ```
> 
> Could you tell me if this works?

thank you! it works!

**Comment by kemenaran** [comment]
Great; thanks for the report :)
