### ISSUE TITLE
Could not complete the operation 'Install the 'mattermost' app'

### ISSUE THREAD

**Issue by strasbourgcurieux** [YunoHost-Apps/mattermost_ynh#167]
Bonjour

Could not complete the operation 'Install the 'mattermost' app'. Please provide the full log of this operation by clicking here to get help
https://paste.yunohost.org/raw/qonufuyino

Yunohost 3.7.0.12

Cordialement

**Comment by kemenaran** [comment]
Effectivement, il y a un souci. La raison semble être indiquée dans les logs :

> 2020-03-31 05:27:52,178: WARNING - Mattermost requires an x86_64 machine, but this one is 'i686'.

Mattermost ne tourne que sur les machines 64 bits, or ici le script a détecté un système 32 bits. Je crois que c'est ça qui pose souci.

**Comment by strasbourgcurieux** [comment]
Ok merci
