### ISSUE TITLE
[install] ERROR 1008 (HY000) at line 1: Can't drop database 'mattermost'; database doesn't exist  

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#18]
hi, 
i can't install, like it was a ghost database mattermost ^^
```
Attention : ERROR 1008 (HY000) at line 1: Can't drop database 'mattermost'; database doesn't exist
Attention : mattermost n'a pas été supprimé correctement
Erreur : Échec de l'installation

```
how can i clean the situation ?

**Comment by kemenaran** [comment]
Well, actually this message is probably the script trying to clean things up after an error (and failing to do so). But there must have been another error earlier during the installation.

Do you have the full log of the installation?

**Comment by kemenaran** [comment]
This issue looks stalled. Probably this will be caught by the test branch I'm currently working on.
