### ISSUE TITLE
Add a package for Matterbridge

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/mattermost_ynh#188]
Do you have any thoughts on the implementation of [Matterbridge](https://github.com/42wim/matterbridge) on Yunohost? Is it something that might work and is doable? Any plans for it?
I can see that Univention (simlar platform to Yunohost) has [implemented](https://www.univention.com/products/univention-app-center/app-catalog/matterbridge/) Matterbridge as an application.

**Comment by kemenaran** [comment]
Oh, I didn't knew that Matterbridge existed. It looks like a very useful and complete project.

I guess, if it was integrated into Yunohost, it would probably be a separate Yunohost package, installed aside the Mattermost package.

However it sounds the configuration is mainly done by scripting, and i don't know how well it would integrate into yunohost GUI. But it is probably possible, yes.

I'm currently a bit busy by Life™, so I won't be able to implement this myself. However a good next step, if you want, could be to add Matterbridge to a list of wanted apps (maybe on Yunohost forums?)

**Comment by anubister** [comment]
There is already a YNH package : https://github.com/YunoHost-Apps/matterbridge_ynh :)

**Comment by hermann-san** [comment]
indeed. It's just that it's not available in the admin GUI

**Comment by ericgaspar** [comment]
Matterbridge as just been repackaged : https://github.com/YunoHost-Apps/matterbridge_ynh

**Comment by hermann-san** [comment]
great news.
I hope YH team will update their webpage soon because it still show's up as "not working" in the [app catalog](https://yunohost.org/#) Maybe it takes a few days.

**Comment by kemenaran** [comment]
Anyway the app is available as a separate package, so I'm closing this issue.
