### ISSUE TITLE
update to mainstream please

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#198]
https://mattermost.atlassian.net/browse/MM-31171
could we upgrade to `v5.30` please ?

thx for you work ;)

@isAAAc

**Comment by kemenaran** [comment]
Mattermost v5.30 is not released yet. But as soon as it will be, this package will be upgraded too :)

**Comment by kemenaran** [comment]
(Closing until the next release.)
