### ISSUE TITLE
can no longer install Mattermost

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/mattermost_ynh#204]
I can no longer install Mattermost on 2 of my yunohost servers (using latest and updated YNH 4 / Debian 10).

I got this error: 
"2021-01-14 10:36:39,690: ERROR - Impossible d’installer mattermost : Une erreur est survenue dans le script d’installation de l’application"

which is not very informative...

https://paste.yunohost.org/raw/vumapuhodu

**Comment by kemenaran** [comment]
Yes, indeed, it seems this package is broken under YNH 4.

Fortunately @ericgaspar rewrote almost the entire packaging script, and even added new features. So hopefully once #203 is merged, this should work again.

**Comment by kemenaran** [comment]
@farvardin hopefully this is fixed by now; closing this issue.
