### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by NathanRussellUK** [YunoHost-Apps/mattermost_ynh#207]
Due to the problems with the nohost.me DDOS yesterday, I tried to change the Mattermost URL to a domain of our own, so that we could continue to access it, but the button in the YunoHost admin UI was disabled.

Is it possible to change the URL of a Mattermost app already installed?

(If we uninstall and reinstall Mattermost the chat history will presumably be lost)

Thanks

Nathan

**Comment by kemenaran** [comment]
It is not possible yet, but it will be soon: as soon as #203 is merged to the main branch, the button to change the URL will be available.

In the meantime, if you feel adventurous, you can try to install this PR locally before it is merged, using `sudo yunohost app upgrade mattermost --url https://github.com/YunoHost-Apps/mattermost_ynh/tree/pull/203/head`. But be careful: this is a large refactoring of the packaging system, and although it _should_ work, it has not been extensively tested yet :)

**Comment by NathanRussellUK** [comment]
That's fantastic - thanks very much! Not feeling very adventurous, but happy to wait :)

**Comment by kemenaran** [comment]
Er, my bad: I though the change_url script would be included in the linked PR, but it is not.

We'll try to have a shot at it soon though.

**Comment by NathanRussellUK** [comment]
Hello - am I right in thinking that as the merge request is now resolved, everything should be on master and ready to go?
I'm on 5.30.1~ynh1, and I don't think there are any more updates, but I'm not yet able to so just clarifying! :)

Thanks so much for looking into it - really appreciate it and if there's any way I can support development, let me know

**Comment by kemenaran** [comment]
Yep, that's done on master. Thanks for the supporting proposal; opening issues if anything is broken is always appreciated :)
