### ISSUE TITLE
Eror 404: not found during install

### ISSUE THREAD

**Issue by punkrockgirl** [YunoHost-Apps/mattermost_ynh#222]
Raspberry Pi 4B
Yunohost: 4.1.7.2

I have tried both GUI and terminal —master and testing branch— to install Mattermost but there seems to be a problem:

`ERROR 404: Not Found. https://github.com/SmartHoneybee/ubiquitous-memory/releases/download/v5.31.0/mattermost-v5.31.1-linux-arm.tar.gz`

Full log: https://paste.yunohost.org/raw/juwobarana

While documentation lists 5.32.1, the script seems to call an older version.

**Comment by kemenaran** [comment]
Oops, indeed: I forgot to update both version numbers in this URL.

This should be fixed once #223 is merged. Sorry, and thanks for the report!

**Comment by kemenaran** [comment]
The ARM package should now work again. Can you try to install it again?

**Comment by punkrockgirl** [comment]
I confirm that it works.

Took 2 minutes using GUI.

Thank you very much!
