### ISSUE TITLE
Upcoming breaking change when using Mattermost with a reverse proxy

### ISSUE THREAD

**Issue by jasonblais** [YunoHost-Apps/mattermost_ynh#23]
My name is Jason Blais and I'm a product manager for the Mattermost open source project.

Mattermost is moving to new APIv4 endpoints, which will allow for more powerful integrations and server interaction.

As part of this move, we will be moving the WebSocket endpoint to APIv4 in Q3 of 2017 (tentatively scheduled for July 16, 2017 release). This will result in a breaking change for deployments using a reverse proxy.

For those configuring NGINX proxy, just a single one-line change is required, replacing the `location /api/v3/users/websocket {` line with `location ~ /api/v[0-9]+/(users/)?websocket$ {` in the `/etc/nginx/sites-available/mattermost` NGINX configuration file. [We've noted this in our documentation](https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-as-a-proxy-for-mattermost-server).

I'm opening an issue so we can discuss if any changes are needed for the Yunohost package, as we weren't sure what kind of configuration is recommended on your end.

**Comment by kemenaran** [comment]
Hi @jasonblais,

Thanks for the message. This package defines the nginx configuration in the [conf/nginx.conf-nosub](https://github.com/YunoHost-Apps/mattermost_ynh/blob/master/conf/nginx.conf-nosub) file. And truth to be told, I never included the old `api/v3` config line in the template.

I guess this means I'll need to :

- Add the new line to the nginx config file _(for new installs)_
- Ensure that the `upgrade` script can insert the line to existing config files _(for upgrades)_

**Comment by jasonblais** [comment]
Thanks @kemenaran, that sounds correct.

**Comment by kemenaran** [comment]
This has been fixed in aaec1ec07c864691d157452ff7288bdc9eac4cfe, along with the 4.0 release. @jasonblais  Thanks for the heads-up!
