### ISSUE TITLE
Protect the `testing` branch

### ISSUE THREAD

**Issue by kemenaran** [YunoHost-Apps/mattermost_ynh#256]
I'd like to protect the `testing` branch against unwanted deletions.

There's a setting for this in Github, but I don't have access rights to the repo Settings.

@ericgaspar do you think you could add a branch protection – or grant me admin rights on this repo?

**Comment by ericgaspar** [comment]
You should have admin rights now. Can you confirm?

**Comment by kemenaran** [comment]
Yes, it works, I see the "Settings" tab. Thanks!

**Comment by kemenaran** [comment]
And done: the `master` and `testing` branch are protected against force-pushes and unwanted deletion.
