### ISSUE TITLE
Remove analytics

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/mattermost_ynh#26]
Mattermost use some analytics from [segment.com](https://segment.com/)
You can see them from the console of your browser.

Please remove this by a patch. It's not really what we expected from a open source app !
And more from a YunoHost app !

**Comment by jasonblais** [comment]
Hey @maniackcrudelis, you can disable diagnostics and error reporting from the System Console: https://docs.mattermost.com/administration/config-settings.html#enable-diagnostics-and-error-reporting

Here's more info on telemetry: https://docs.mattermost.com/administration/telemetry.html

**Comment by maniackcrudelis** [comment]
Thanks @jasonblais for this information.

**Comment by kemenaran** [comment]
@maniackcrudelis this has been merged ; closing this issue. Thanks for your work!
