### ISSUE TITLE
500 error when editing instance settings

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/mattermost_ynh#27]
Hello,
I'v installed the packaged on a server with : 
64Bit
12 GB of RAM

and I get an error when I want to change settings (passwd, main URL,...) : 
"We received an unexpected status code from the server. (500)"

Have you got any idea to solve it ?
Thanks,
frju365

**Comment by tibs245** [comment]
This is after a restart ?

**Comment by frju365** [comment]
no, just when I wanted to change the setting, just after having installed the app from the admin interface.

**Comment by kemenaran** [comment]
Mmh, it could be a permission issue on the `config.json` file.

@frju365 Do you have an SSH access to your Yunohost instance? If so, could you execute `ls -l /var/www/mattermost/config` in a terminal, and paste the result here?

**Comment by kemenaran** [comment]
@frju365 I need additional details from you. Could you execute `ls -l /var/www/mattermost/config` on your Yunohost server, and paste the result here?

Until I get these logs, I'm afraid there isn't much I can do. I'm closing this issue for now.
