### ISSUE TITLE
Cannot connect to server on iOS app

### ISSUE THREAD

**Issue by w0ns88** [YunoHost-Apps/mattermost_ynh#285]
Hello,

I am not sure if this is for the right place, but someone might be able to help out.

I have added mattermost on my yunohost self hosted server.

It resides on one of my subdomains (example): chat.mydomain.com

I have then downloaded the mattermost ios app so I could use my own on my phone. But each time I try to add the server: https://chat.mydomain.com to the "Enter Server URL" screen on the app. I keep getting the same error: 

```
Cannot connect to ther server. Please check your server URL and internet connection.
```

Both my internet connections and Server URL are correct. I have checked the SSL and it's set up via Let's Encrypt as configured in Yunohost.

The next thing to check is the proxy configuration, but I am unsure what I should look at there. 

Has anyone encountered this problem and can maybe help out?

Thanks in advance!

**Comment by ericgaspar** [comment]
Make sure you have `is public` set to **yes** during install.

**Comment by w0ns88** [comment]
Yes that was it. Thanks @ericgaspar
