### ISSUE TITLE
Can't restore mattermost app

### ISSUE THREAD

**Issue by narduin** [YunoHost-Apps/mattermost_ynh#287]
### Describe the bug

Hello, I first published my issue on the yunohost forums [here](https://forum.yunohost.org/t/mattermost-restore-failed/17099) without luck.

I'm trying to migrate a complete server to a new one. Everyhting works fine except for the mattermost app.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: *Full migration from a built-in backup*

### Steps to reproduce

I don't know if it can be reproduced, I have not tested on a clean install yet.

- Install yunohost
- install mattermost
- create a full backup
- `sudo yunohost backup create`
- try restoring this backup to another fresh yunohost server instead of the post-install step
- `sudo yunohost backup restore`

### Expected behavior

Mattermost should be restored from the backup.

### Logs

[Here are the logs](https://paste.yunohost.org/raw/ocuyopupad) of today's attempt.

**Comment by kemenaran** [comment]
Thanks for the reports and the logs, and sorry for the issue.

It looks like the restore process went smoothly, but at the end the mattermost server failed to start.

Do you by any chance have the logs of the Mattermost server, either in journalctl or in /var/log/mattermost ?

**Comment by kemenaran** [comment]
Some progress: from your install logs, the database user that was created on restore is named `mattermost` – but the Mattermost's config.json file instructs the server to connect with a user named `mmuser`.

It looks like an ancient db username wasn't carried over during restore.

The good news is that you can fix your Mattermost installation, by editing `/var/www/mattermost/config/config.json`, and changing the setting `SqlSetting > DataSource` like this:

```diff
-     "DataSource": "mmuser:*******@tcp(localhost:3306)/mattermost?charset=utf8mb4,utf8",
+     "DataSource": "mattermost:********@tcp(localhost:3306)/mattermost?charset=utf8mb4,utf8",
```

I'll also try to fix the restore script so that it doesn't append in the future (although this won't automatically fix old backups, it will fix the issue for newer ones).

**Comment by kemenaran** [comment]
See #289 for the technical issue.

**Comment by narduin** [comment]
THANK YOU @kemenaran !!

```bash
Info: Restoring mattermost...
Info: [+...................] > Loading installation settings...
Info: [#+..................] > Validating restoration parameters...
Info: [##+.................] > Recreating the dedicated system user...
Info: [###++...............] > Restoring the app main directory...
Info: [#####++++...........] > Restoring the data directory...
Info: [#########++++++.....] > Restoring the MySQL database...
Info: [###############++...] > Starting a systemd service...
Info: The service mattermost has correctly executed the action start.
Info: [#################+..] > Reloading NGINX web server...
Info: [####################] > Restoration completed for mattermost
```
