### ISSUE TITLE
Unable to install Mattermost

### ISSUE THREAD

**Issue by g0eki** [YunoHost-Apps/mattermost_ynh#307]
Hello everyone, 
I am new and it is my first issue report.

I get the error message every time:
Error: Unable to install mattermost: An error occurred inside the app installation script

I tried to install it normally via web browser and via the terminal.

Here is my full Report:
via Web Browser:
https://paste.yunohost.org/raw/teyehoqila
via Terminal:
https://paste.yunohost.org/raw/xosalejiji

My Device: Raspberry PI 3

I hope someone can help me. :) 
I have to apologize for my bad English and Thank you

**Comment by kemenaran** [comment]
Hi @g0eki, thanks for the bug report. That looks like an issue we just identified when installing this package on ARM platforms (like a Raspberry Pi). We're discussing the issue there (#306), but a fix was just merged, and should be live in the Web Admin in a few hours.

Meanwhile you can try to install the fixed version right now through the terminal, by executing:

```
sudo yunohost app install https://github.com/YunoHost-Apps/mattermost_ynh/tree/master
```

Does it work better for you?

**Comment by g0eki** [comment]
Hi @kemenaran,
thank you this works for me. :+1:
