### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mattermost_ynh#34]
The app don't open in https itself and https has to be manually typed so that app can use secure connection.

**Comment by kemenaran** [comment]
You're right, this should be done.

**Comment by anmol26s** [comment]
This is the nginx configuration for force https :

# Force https
  if ($scheme = http) {
    rewrite ^ https://$server_name$request_uri? permanent;
  }

**Comment by nemsia** [comment]
Redirect to ssl : https://github.com/YunoHost-Apps/mattermost_ynh/pull/75

**Comment by kemenaran** [comment]
Fixed by #75. Thanks @nemsia!
