### ISSUE TITLE
This version of Mattermost doesn't work with the Android app

### ISSUE THREAD

**Issue by coopbourgogne** [YunoHost-Apps/mattermost_ynh#35]
Hi, thanks for your work.

I just wanted to point out that the Android app was not working with the current version of the Mattermost package for Yunohost.

Thanks again to you

**Comment by kemenaran** [comment]
Hmm, interesting—I believe it should.

Do you know the version (or build number) of the Android app you are using? Is it the "Mattermost classic" version—or the new "Mattermost" app (which was rewritten recently using React Native) ?

**Comment by coopbourgogne** [comment]
Thanks for your reply.

The version of the android app is the 1.1.0 and i use the new app (com.mattermost.rn) and not the old one (com.mattermost.mattermost)

**Comment by coopbourgogne** [comment]
I don't know if you need this information but the version of the webapp is 3.9.0.

**Comment by daftaupe** [comment]
Hello,

I have the same issue and on the page of the application : https://play.google.com/store/apps/details?id=com.mattermost.rn
It's clearly written that it won't work "for a v3.10+ Mattermost server"

**Comment by kemenaran** [comment]
Yes, you may need to upgrade your Mattermost instance on Yunohost to the latest server version.

For what is worth, this `mattermost_ynh` app currently installs or upgrade Mattermost 4.1.

**Comment by kemenaran** [comment]
Closing this issue, since it seems to be a version mismatch issue.
