### ISSUE TITLE
Use mmctl CLI command

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/mattermost_ynh#361]
### Describe the bug

The CLI command `mmctl` can't be performed

### Context

- Hardware: *VPS bought online 
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
- Using package version/branch: 6.6.1~ynh1

### Steps to reproduce

 ```
/var/www/mattermost# sudo -u mattermost bin/mmctl user list
 ```
return

```
Error: cannot read user credentials, maybe you need to use login first: stat /var/www/mattermost/.config/mmctl/config: no such file or directory

```

### Expected behavior

The result of the CLI command `bin/mmctl`

### Logs

 It seems it is looking for a false url `/var/www/mattermost/.config/mmctl/config`

**Comment by kemenaran** [comment]
Yup! That's not very intuitive, but expected: mmctl has to be connected to the local mattermost instance using proper credentials before it can perform actions.

You can read an HOWTO for this on the mattermost_ynh wiki: https://github.com/YunoHost-Apps/mattermost_ynh/wiki

Does that solve your issue?

**Comment by rodinux** [comment]
Yes, it solve my issue. Thanks you so much !

**Comment by rodinux** [comment]
solved

**Comment by TheNomad11** [comment]
> You can read an HOWTO for this on the mattermost_ynh wiki: https://github.com/YunoHost-Apps/mattermost_ynh/wiki

The wiki disappeared. What happened?

**Comment by kemenaran** [comment]
It seems the wiki was disabled a while ago. I just re-enabled it, so the link works again.

@ericgaspar anything opinion on wiki for Yunohost packages? Or a better place to put this documentation?
