### ISSUE TITLE
MariaDB not supported: migrate to PostgreSQL?

### ISSUE THREAD

**Issue by biva** [YunoHost-Apps/mattermost_ynh#367]
Hello,

I read on this thread from the francophone Mattermost community that MariaDB could create issues, and that Mattermost only supports MySQL and PosgreSQL: https://twitter.com/MattermostFR/status/1534838198286929920 Maybe @amyblais could confirm if it's true? It looks confirmed if I read the documentation: https://docs.mattermost.com/install/software-hardware-requirements.html#database-software

> MariaDB v10+ no longer functions as a MySQL drop-in replacement, and it’s not supported for Mattermost due to the requirement of MySQL 5.7.12. Prior versions of MariaDB were not officially supported but may have functioned in older Mattermost releases. If you are running MariaDB now, migrating from MariaDB to the MySQL equivalent is recommended.

I'm not sure about what is used in this Yyunohost package? I see MySQL in https://github.com/YunoHost-Apps/mattermost_ynh/blob/master/scripts/install, but maybe it's MariaDB behind that?

Would you consider using PostgreSQL to secure a stable installation?

**Comment by amyblais** [comment]
Correct, we don't support MariaDB. There is also some more details in this thread here https://community.mattermost.com/core/pl/5m9mnur4ejn9z8c7c9dipaw7jc.

**Comment by kemenaran** [comment]
The script indeed doesn't mention MariaDB: it requests a MySQL setup from the distro. If the distro provides MariaDB instead, that's probably up to ensure the compatibility.

Migrating new installations to Postgres would be nice, but I'm afraid of the migration, and of supporting some setups on MariaDB and some others on Postgres (like how do we restore an older backup? Do we need both code paths?)

**Comment by biva** [comment]
Thanks @kemenaran, as far as I understand, Postgres is the preferred version, advised by Mattermost. While I also understand that Debian ships MariaDB by default (if I trust this: https://www.how2shout.com/linux/how-to-install-mysql-8-0-server-on-debian-11-bullseye/).

I think the safest solution would be to go for Postgres for all new installation. For old installation, I would push a migration. There's an existing discussion here, notably around pgloader: https://github.com/mattermost/mattermost-server/issues/18351

pgloader is notably advised by @wget in its tweet to the francophone community: https://twitter.com/MattermostFR/status/1534838206738403329

**Comment by biva** [comment]
Hello @kemenaran,

Mattermost is confirming that MariaDB is really not supported at all and might create issues. Would it be possible to update the script so that it uses PostgreSQL for new installations? It will avoid issues for new users at least.
The script could also - temporarily - block the updates from now on for the ones using MySQL/MariaDB. This leaves some time to find a solution to migrate the existing installations.

What do you think?

**Comment by biva** [comment]
Hello @kemenaran, even if I'm not very skilled, I try to propose a change in the script to install Mattermost with PostgreSQL for new users. Would you be able to help me?

https://github.com/YunoHost-Apps/mattermost_ynh/pull/373
https://github.com/YunoHost-Apps/mattermost_ynh/pull/374

**Comment by lenybernard** [comment]
Upgrading today from 7.2 to 7.3 has broken Boards with the following log :

> Unable to restart plugin on upgrade., error initializing the DB: MariaDB database is not supported, you can find more information at https://docs.mattermost.com/install/software-hardware-requirements.html#database-software

**Comment by kemenaran** [comment]
@lenybernard ouch, thanks for letting us know.

@ericgaspar I'll revert the current upgrade, until the postgres migration is ready. It seems better not to have user pressure when testing the migration :)

**Comment by freddewitt** [comment]
Hello all, i'm a simple user, is they anyway to give help ?
Can we go back to 7.2 without losing what was writing since the 7.3 update ?
Thanks

**Comment by kemenaran** [comment]
I tested reverting to Mattermost 7.2 from a 7.3 install – and it didn't work that well : user sessions were lost, and it seems passwords had to be reinitialized.

So there's no clear solution for making Boards work right now. I'm sorry for the inconvenience.

I guess that :
- on your setup, you can try migrating from MariaDB to MySQL,
- on Yunohost side, we should put more work into the Postgres migration (but it's not an easy task).

**Comment by freddewitt** [comment]
It's weird, because i don't see any mariadb running on my session, only SQL / POSTGRESQL..

**Comment by freddewitt** [comment]
Hello 

`on your setup, you can try migrating from MariaDB to MySQL`

Can you tell us how that could be done ? 
I did install Focalboard, it works well for now, but i rather prefer use it on mattermost :(

thanks for all guys

**Comment by freddewitt** [comment]
Est ce que ça serait pas plus simple d'aller vers MySQL depuis MariaDB ?

Wouldn't it be easier to go to MySQL from MariaDB?

**Comment by ericgaspar** [comment]
Closing with #411

**Comment by biva** [comment]
Yihaa! Congrats :)
