### ISSUE TITLE
Mattermost not restoring

### ISSUE THREAD

**Issue by alfredo87** [YunoHost-Apps/mattermost_ynh#401]
My YunoHost server

Machine ASUSTeK COMPUTER INC./H110T, BIOS 4212 07/24/2019
CPU Number of processors: 4
Intel(R) Core™ i3-6100T CPU @ 3.20GHz 
0%
Intel(R) Core™ i3-6100T CPU @ 3.20GHz 
0%
Intel(R) Core™ i3-6100T CPU @ 3.20GHz 
1%
Intel(R) Core™ i3-6100T CPU @ 3.20GHz 
0%
PCI Number of devices: 14
USB Number of devices: 4
I2C Number of devices: 8

YunoHost version: 11.0.10.2 (stable).
I have access to my server : Through SSH | through the webadmin |
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no
If yes, please explain:

Description of my issue

There was a powercut.
The IP changed
The dynhost reset the IP at OVH
Mattermost service stopped
It did not restart after power returned
I uninstalled mattermost
I restored mattermost from my last backup from this morning
Mattermost restore fails at systemd service restart

Here is the log
https://paste.yunohost.org/raw/yakosinome
IMO this is a permission error. I am thinking of reinstalling and restoring the whole server. Which as I know is bad practice: but how can I restore permissions without the user “Mattermost” in place? He is not visible or known. Mattermost forums are not helpful because the folder and files are different in yunohost compared to standard Debian server!!!???
Please help because this is an important tool for my family!!
Yunohost is a great software system and I am very grateful for your work: that is why I have set up a regular donation!!
Thanks to anybody who can help with this…

Also see this forum post 
https://forum.yunohost.org/t/mattermost-restore-failure/22605

**Comment by Jaxom99** [comment]
Hi there,

I want to make a migration of mattermost from a server to another, and I encounter the same bug. See Log : https://paste.yunohost.org/raw/xajinogago

Any update or workaround ?

**Comment by kemenaran** [comment]
Hmm, we'd need some extra logs to see what is the precise issue that prevents the Mattermost server from starting after a backup restore. What is the output of `systemctl status mattermost.service` and `journalctl -xe"` after the failure?

**Comment by Jaxom99** [comment]
I have this
```
# systemctl status mattermost.service
● mattermost.service
     Loaded: not-found (Reason: Unit mattermost.service not found.)
     Active: failed (Result: exit-code) since Fri 2023-04-07 12:39:51 CEST; 1h 10min ago
   Main PID: 270176 (code=exited, status=1/FAILURE)
        CPU: 0

Apr 07 12:39:47 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.
Apr 07 12:39:47 metanum.fr systemd[1]: Failed to start Mattermost.
Apr 07 12:39:51 metanum.fr systemd[1]: mattermost.service: Failed to schedule restart job: Unit mattermost.service not found.
Apr 07 12:39:51 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.

```
And this
```
# journalctl -u mattermost
-- Journal begins at Fri 2023-03-17 11:07:23 CET, ends at Fri 2023-04-07 13:50:32 CEST. --
Apr 07 12:36:56 metanum.fr systemd[1]: Starting Mattermost...
Apr 07 12:39:47 metanum.fr systemd[1]: mattermost.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 12:39:47 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.
Apr 07 12:39:47 metanum.fr systemd[1]: Failed to start Mattermost.
Apr 07 12:39:51 metanum.fr systemd[1]: mattermost.service: Failed to schedule restart job: Unit mattermost.service not found.
Apr 07 12:39:51 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.

```

It may be due to the fact that yunohost removes everything when the restore operation fails (?).

I'm trying the fix proposed by Alex on the forum (modifying the mattermost.service file, adding a "server" argument) and I report back here

**Comment by Jaxom99** [comment]
Same error again, after editing the .service file in the archive : 
```
# journalctl -xe
░░ An ExecStart= process belonging to unit mattermost.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Apr 07 14:48:56 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit mattermost.service has entered the 'failed' state with result 'exit-code'.
Apr 07 14:48:56 metanum.fr systemd[1]: Failed to start Mattermost.
░░ Subject: A start job for unit mattermost.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit mattermost.service has finished with a failure.
░░ 
░░ The job identifier is 94069 and the job result is failed.
Apr 07 14:48:59 metanum.fr systemd[1]: Configuration file /etc/systemd/system/mattermost.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restriction>
Apr 07 14:48:59 metanum.fr systemd[1]: Reloading.
Apr 07 14:48:59 metanum.fr systemd[1]: Configuration file /etc/systemd/system/hedgedoc.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions.>
Apr 07 14:48:59 metanum.fr systemd[1]: Configuration file /etc/systemd/system/mattermost.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restriction>
Apr 07 14:48:59 metanum.fr systemd[1]: Reloading.
Apr 07 14:48:59 metanum.fr systemd[1]: Configuration file /etc/systemd/system/hedgedoc.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions.>
Apr 07 14:48:59 metanum.fr systemd[1]: mattermost.service: Failed to schedule restart job: Unit mattermost.service not found.
Apr 07 14:48:59 metanum.fr systemd[1]: mattermost.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit mattermost.service has entered the 'failed' state with result 'exit-code'.

```

**Comment by Jaxom99** [comment]
I decided to upgrade the app prior to migration : it went from 7.2 to 7.8 (with mysql to pgsql change) without trouble. And the backup-transfer-restore process was successful :tada: 
I must point I'm using the Entreprise edition.

Good luck alfredo, on my part the issue is resolved...

**Comment by alexAubin** [comment]
(This person had the same issue again today and this was due to `UseLetsEncrypt` being set to true instead of false in config/config.json ...)
