### ISSUE TITLE
Tips: running a mmctl command in local mode

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/mattermost_ynh#405]
sudo -u mattermost MMCTL_LOCAL_SOCKET_PATH=/var/run/mattermost/mattermost_local.socket bin/mmctl team list --local

**Comment by kemenaran** [comment]
Thanks for the tip!

For what is worth, this in covered with more details in the wiki (https://github.com/YunoHost-Apps/mattermost_ynh/wiki), but I should add more links to it, so that it is easier to find.
