### ISSUE TITLE
Failed to upgrade Mattermost app on self hosted yunohost server

### ISSUE THREAD

**Issue by systemop7** [YunoHost-Apps/mattermost_ynh#422]
I am facing this problem when I want to upgrade my Mattermost app from my self hosted yunohost server..

```sh
2023-03-31 11:37:22,259: DEBUG - + sudo -u mattermost timeout --preserve-status 180 ./bin/mattermost

2023-03-31 11:37:22,288: WARNING - timeout: failed to run command ‘./bin/mattermost’: Permission denied 
```

Version: YunoHost 11.1.19

## Full Error Log
[Error Log](https://paste.yunohost.org/raw/vewofeponu)

**Comment by systemop7** [comment]
Hello @kemenaran 
Thanks a lot for your response



```
admin@username:~$ sudo yunohost app upgrade mattermost__2 --url https://github.com/YunoHost-Apps/mattermost_ynh/tree/fix-migration-user
Info: Now upgrading mattermost__2...
Info: [+...................] > Loading installation settings...
Info: [#...................] > Checking version...
Info: [#+..................] > Backing up the app before upgrading (may take a while)...
Info: [##++++++............] > Upgrading dependencies...
Info: Migrating to PostgreSQL database...
Warning: ERROR 1146 (42S02) at line 1: Table 'mattermost.Users' doesn't exist
Warning: [Error] Upgrade failed.
Warning: The app was restored to the way it was before the failed upgrade.
Error: Could not upgrade mattermost__2: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'mattermost__2' app' could not be completed. Please share the full log of this operation using the command 'yunohost                                                                                         log share 20230526-085151-app_upgrade-mattermost__2' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + ynh_psql_connect_as --user=postgres --password=********** --database=mattermost__2
Info: DEBUG - + database=mattermost__2
Info: DEBUG - + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql mattermost__2
Info: DEBUG - DROP INDEX
Info: DEBUG - + ynh_psql_execute_as_root '--sql=DROP INDEX public.idx_posts_message_txt;' --database=mattermost__2
Info: DEBUG - + database=mattermost__2
Info: DEBUG - + '[' -n mattermost__2 ']'
Info: DEBUG - + database=--database=mattermost__2
Info: DEBUG - ++ cat /etc/yunohost/psql
Info: DEBUG - + ynh_psql_connect_as --user=postgres --password=********** --database=mattermost__2
Info: DEBUG - + database=mattermost__2
Info: DEBUG - + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql mattermost__2
Info: DEBUG - DROP INDEX
Info: DEBUG - + ynh_mysql_execute_as_root '--sql=ALTER TABLE mattermost.Users DROP COLUMN IF EXISTS acceptedtermsofserviceid;' --database=mattermost_                                                                                        _2
Info: DEBUG - + database=mattermost__2
Info: DEBUG - + '[' -n mattermost__2 ']'
Info: DEBUG - + database=--database=mattermost__2
Info: DEBUG - + mysql -B --database=mattermost__2
Info: WARNING - ERROR 1146 (42S02) at line 1: Table 'mattermost.Users' doesn't exist
Info: DEBUG - + ynh_exit_properly
Error: The operation 'Upgrade the 'mattermost__2' app' could not be completed. Please share the full log of this operation using the command 'yunohos                                                                                        t log share 20230526-085151-app_upgrade-mattermost__2' to get help
```

**Comment by kemenaran** [comment]
Thank for trying the upgrade! Mmm, I have no idea why MySQL's mattermost.Users table would not exist…

If you open a shell, and connect manually to MySQL's `mattermost_2` database, do you see a mattermost.Users table? Or is the prefix different?

**Comment by systemop7** [comment]
First of all Thank you so much [kemenaran](https://github.com/kemenaran)  for supporting me to solve this issue

now i am facing this issue

```sh
An error occurred inside the app upgrade script
```

Version: YunoHost 11.1.19

## Full Error Log
[Error Log](https://paste.yunohost.org/raw/usojumowuy)

**Comment by kemenaran** [comment]
This may be improved by the switch to manifest v2 (which has been merged into master recently).

**Comment by systemop7** [comment]
##  **Initial Attempts:**

I initially posted an issue about this on the Mattermost GitHub issue section, hoping for a quick resolution. However, I couldn't find a way to resolve the problem through GitHub assistance.
## **Solution**:

After some investigation, I decided to rename my database from mattermost__2 to simply mattermost. Here's how I did it:

**Backup the Database:**
 Before making any changes, I backed up my existing mattermost__2 database to ensure data integrity.

**Rename the Database**: 
I logged into my SQL management tool and executed the following SQL query to rename the database:

    RENAME DATABASE mattermost__2 TO mattermost;

**Update Configuration:** 
I also updated the config.json file for Mattermost to reflect the new database name.

 **Restart Services:** 
Finally, I restarted the Mattermost and SQL services to make sure the changes took effect.

After performing these steps, the issue was resolved. Mattermost was able to locate the required tables, as they now matched the mattermost.* naming convention it was expecting.
Recommendation:

If you're facing a similar issue, ensure that your database name aligns with what Mattermost expects to avoid any discrepancies that could result in application errors.

I hope this summary helps anyone else encountering a similar issue.

Specially thanks @kemenaran for help me a lot..

**Comment by kemenaran** [comment]
Thanks for the summary! Hopefully with the new manifest it should be better now – but this could definitely help people migrating from older versions.
