### ISSUE TITLE
Is Bulk export working with mattermost / yunohost ?

### ISSUE THREAD

**Issue by freddewitt** [YunoHost-Apps/mattermost_ynh#425]
Hello,

Not a bug i guess, but i'am looking after bulk export to save my mattermost session beforce making a clean install of yunohost (it's not working anymore). In the mattermost documentation ( [here](https://docs.mattermost.com/manage/bulk-export-tool.html)) , i have to go to the bin directory and to find mattermost binairies.

but where is it ? In the yunohost home, it's seems to been not binairies.

Thansk for the help!

**Comment by kemenaran** [comment]
Good question! The dedicated wiki page should help you to find the [mmctl location on your Yunohost instance](https://github.com/YunoHost-Apps/mattermost_ynh/wiki). (I'm trying to get this indexed by search engines).

**Comment by TheNomad11** [comment]
Maybe helpful to note that the export file is located in /home/yunohost.app/mattermost/export
