### ISSUE TITLE
Add a Howto for migrating to MariaDB

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#76]
hi, 
i would install matermost since a long time but can't because my mysql version wasn't good as said in the readme.md , 
i migrate it to mariadb as explained in https://forum.yunohost.org/t/impossible-dinstaller-mattermost-en-commande-de-ligne/3191/7 with success, 
so i purpose including this "tips" in the readme.md 

i still have a 502 error, but i think it's another trouble not linked with the db version ;) 
the install ended with success

**Comment by kemenaran** [comment]
Thanks for the suggestion. I agree a hint in the README could be a good idea – but it also seems a bit dangerous to me. Switching the database engine on an old distrib _should_ work, but it requires the user to know what they're doing, probably a backup, etc.

So I'm afraid that people could just copy-paste a random snippet from this README to upgrade to MariaDB, and end up with a entirely borked system if the migration goes wrong. I would prefer not to take responsibility for this operation, and leave it to websites and people who know better than me how to migrate.
