### ISSUE TITLE
502 Bad Gateway after install

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#77]
Hi , 
could someone help me to debug please ?
i just installed mattermost, but it's like the service is unknown by the system ...

 yunohost -v
> yunohost: 2.7.2
> yunohost-admin: 2.7.2
> moulinette: 2.7.2
> ssowat: 2.7.2

install log : 

> 
> 2017-12-01 00:18:18,660 INFO     yunohost.hook <lambda> - [31160.1] + sudo cp /var/cache/yunohost/from_file/mattermost_ynh-8295da93cd36c66bf27e9b0082514f1dce255ba5/scripts/../conf/nginx.conf-nosub /etc/nginx/conf.d/mat.krashboyz.org.d/mattermost.conf
> 2017-12-01 00:18:18,675 INFO     yunohost.hook <lambda> - [31160.1] + sudo cp /var/cache/yunohost/from_file/mattermost_ynh-8295da93cd36c66bf27e9b0082514f1dce255ba5/scripts/../conf/supervisor.conf /etc/supervisor/conf.d/mattermost.conf
> 2017-12-01 00:18:18,690 INFO     yunohost.hook <lambda> - [31160.1] + sudo yunohost app setting mattermost is_public -v Yes
> 2017-12-01 00:18:18,953 INFO     moulinette.actionsmap process - processing action [31278.1]: yunohost.app.setting
> 2017-12-01 00:18:18,979 INFO     yunohost.hook <lambda> - [31160.1] + '[' Yes = Yes ']'
> 2017-12-01 00:18:18,980 INFO     yunohost.hook <lambda> - [31160.1] + sudo yunohost app setting mattermost unprotected_uris -v /
> 2017-12-01 00:18:19,246 INFO     moulinette.actionsmap process - processing action [31282.1]: yunohost.app.setting
> 2017-12-01 00:18:19,274 INFO     yunohost.hook <lambda> - [31160.1] + sudo service nginx reload
> 2017-12-01 00:18:19,540 INFO     yunohost.hook <lambda> - [31160.1] + sudo yunohost app ssowatconf
> 2017-12-01 00:18:19,831 INFO     moulinette.actionsmap process - processing action [31294.1]: yunohost.app.ssowatconf
> 2017-12-01 00:18:21,837 INFO     yunohost.app app_setting - [31294.1] cannot get app setting 'update_time' for 'mattermost'
> 2017-12-01 00:18:22,119 SUCCESS  yunohost.app success - [31294.1] La configuration de SSOwat a été générée
> 2017-12-01 00:18:22,120 INFO     yunohost.hook <lambda> - [31160.1] La configuration de SSOwat a été générée
> 2017-12-01 00:18:22,147 INFO     yunohost.hook <lambda> - [31160.1] + sudo supervisorctl reload
> 2017-12-01 00:18:22,601 INFO     yunohost.hook <lambda> - [31160.1] Restarted supervisord
> 2017-12-01 00:18:25,082 SUCCESS  yunohost.app success - [31160.1] La configuration de SSOwat a été générée
> 2017-12-01 00:18:25,083 SUCCESS  yunohost.app success - [31160.1] Installation terminée

mattermost log : 

more /var/log/mattermost.logmattermost.log   <---------------- strange name for the logfile ^^

> [2017/12/01 00:18:24 CET] [INFO] Loaded system translations for 'en' from '/var/www/mattermost/i18n/en.json'
> [2017/12/01 00:18:24 CET] [INFO] Current version is 4.0.0 (4.0.2/Fri Jul 28 19:49:45 UTC 2017/f71cc067faf935b95ba6fd9e4b24ce5496ab62b9/none)
> [2017/12/01 00:18:24 CET] [INFO] Enterprise Enabled: false
> [2017/12/01 00:18:24 CET] [INFO] Current working directory is /var/www/mattermost
> [2017/12/01 00:18:24 CET] [INFO] Loaded config file from /var/www/mattermost/config/config.json
> [2017/12/01 00:18:24 CET] [INFO] Server is initializing...
> [2017/12/01 00:18:24 CET] [INFO] Pinging SQL master database
> [2017/12/01 00:18:24 CET] [INFO] The database schema has been set to version 4.0.0
> [2017/12/01 00:18:24 CET] [CRIT] Failed to create index Error 1214: The used table type doesn't support FULLTEXT indexes
> [2017/12/01 00:18:26 CET] [INFO] Loaded system translations for 'en' from '/var/www/mattermost/i18n/en.json'
> [2017/12/01 00:18:26 CET] [INFO] Current version is 4.0.0 (4.0.2/Fri Jul 28 19:49:45 UTC 2017/f71cc067faf935b95ba6fd9e4b24ce5496ab62b9/none)
> [2017/12/01 00:18:26 CET] [INFO] Enterprise Enabled: false
> [2017/12/01 00:18:26 CET] [INFO] Current working directory is /var/www/mattermost
> [2017/12/01 00:18:26 CET] [INFO] Loaded config file from /var/www/mattermost/config/config.json
> [2017/12/01 00:18:26 CET] [INFO] Server is initializing...
> [2017/12/01 00:18:26 CET] [INFO] Pinging SQL master database
> [2017/12/01 00:18:26 CET] [CRIT] Failed to create index Error 1214: The used table type doesn't support FULLTEXT indexes
> [2017/12/01 00:18:31 CET] [INFO] Loaded system translations for 'en' from '/var/www/mattermost/i18n/en.json'
> [2017/12/01 00:18:31 CET] [INFO] Current version is 4.0.0 (4.0.2/Fri Jul 28 19:49:45 UTC 2017/f71cc067faf935b95ba6fd9e4b24ce5496ab62b9/none)
> [2017/12/01 00:18:31 CET] [INFO] Enterprise Enabled: false
> [2017/12/01 00:18:31 CET] [INFO] Current working directory is /var/www/mattermost
> [2017/12/01 00:18:31 CET] [INFO] Loaded config file from /var/www/mattermost/config/config.json
> [2017/12/01 00:18:31 CET] [INFO] Server is initializing...
> [2017/12/01 00:18:31 CET] [INFO] Pinging SQL master database
> [2017/12/01 00:18:31 CET] [CRIT] Failed to create index Error 1214: The used table type doesn't support FULLTEXT indexes
> [2017/12/01 00:18:36 CET] [INFO] Loaded system translations for 'en' from '/var/www/mattermost/i18n/en.json'
> [2017/12/01 00:18:36 CET] [INFO] Current version is 4.0.0 (4.0.2/Fri Jul 28 19:49:45 UTC 2017/f71cc067faf935b95ba6fd9e4b24ce5496ab62b9/none)
> [2017/12/01 00:18:36 CET] [INFO] Enterprise Enabled: false
> [2017/12/01 00:18:36 CET] [INFO] Current working directory is /var/www/mattermost
> [2017/12/01 00:18:36 CET] [INFO] Loaded config file from /var/www/mattermost/config/config.json
> [2017/12/01 00:18:36 CET] [INFO] Server is initializing...
> [2017/12/01 00:18:36 CET] [INFO] Pinging SQL master database
> [2017/12/01 00:18:36 CET] [CRIT] Failed to create index Error 1214: The used table type doesn't support FULLTEXT indexes
> 

searching how to make the table supporting FULLTEXT

**Comment by kemenaran** [comment]
@isAAAc thanks for the report. I see two clues there:

- The log file is named `/var/log/mattermost.logmattermost.log`. This was a configuration error during a few releases of this package (something like between Mattermost 3.8 and 4.2). After that, the app log file is named `/var/log/mattermost/mattermost.log`. The upgrade script ought to fix this log file when upgrading, but it may got it wrong somehow. **Was your installation a fresh install, or an upgrade from a former version?**

- The database creation fails. Googling for this error message yields something related to a non-sufficient version of MariaDB (https://stackoverflow.com/questions/25416423/fulltext-indexes-in-mariadb-10). **What is the version of MariaDB you're using?** In any case, if your distribution supports it, I strongly recommend MySQL over MariaDB (not over principles, but because it is officially supported by Mattermost).

**Comment by isAAAc** [comment]
hi @kemenaran , 
* it's a fresh mattermost install 
* mysql version : 

>   # mysql --version
> mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by isAAAc** [comment]
mattermost works fine now, 
i did nothing special :/
