### ISSUE TITLE
Allow installation in sub-directories

### ISSUE THREAD

**Issue by kemenaran** [YunoHost-Apps/mattermost_ynh#8]
For now the installation is only possible at the root of a domain. This is not very flexible, and  prevents installing Mattermost on the main domain of a Yunohost instance.

A configuration option could be added to install Mattermost in a subdirectory if needed.

**Comment by kemenaran** [comment]
**Mattermost doesn't support installation in relative directories for now.**

The issue is being tracked on https://mattermost.atlassian.net/browse/PLT-200.
Upstream contributions to add support for this into Mattermost are welcome.

**Comment by kemenaran** [comment]
Subpath support [has been implemented in Mattermost 5.1](https://docs.mattermost.com/administration/changelog.html#support-mattermost-on-a-subpath).

**Comment by ImaCrea** [comment]
Hello dear @kemenaran would it possible to upgrade the package with Mattermost 5.1 so we could install it on a subdirectory please? 
Restriction to root domain is quiet restrictive as we can't install other apps then :/ (or maybe there's something I havent understood well).

cheers

**Comment by kemenaran** [comment]
Yes, you're right; thanks for the reminder. I'll try to work on this when I'll have spare time.

**Comment by ImaCrea** [comment]
This would be wonderful! I think it would greatly help us share discoveries and then offer even better playlists for the MailTape crew :)

**Comment by win8linux** [comment]
Is there any progress on updating the package to 5.1 or higher @kemenaran?

**Comment by kemenaran** [comment]
The package is actually updated to Mattermost 5.19 – but I didn't took the time to implement a proper configuration for setups in subdirectories yet.

Thanks for reminding it to me though :)

**Comment by kemenaran** [comment]
Support for subpaths has been merged into the `testing` branch.

If you want to test installing Mattermost in a subpath, run the following command on your Yunohost box:

```shell
sudo yunohost app install https://github.com/YunoHost-Apps/mattermost_ynh/tree/testing/
```

Please tell me if you encounter any issues with subpath support.

**Comment by win8linux** [comment]
The install errors out with this:
```
Error: The operation 'Install 'mattermost' application' has failed!
```
[Here](https://paste.yunohost.org/raw/goxuyevuqe) is the log.

**Comment by kemenaran** [comment]
Hmm, from the log, that's because of the password complexity:

> 2020-02-09 12:42:22,637: WARNING - Error: Unable to create user. Error: User.IsValid: Your password must contain at least 10 characters made up of at least one lowercase letter, at least one uppercase letter, at least one number, and at least one symbol (e.g. "~!@#$%^&*()").,

**Comment by win8linux** [comment]
Oh. Would it be possible to prompt a user installing from terminal when they enter a password that's too simple, instead of failing outright?

**Comment by win8linux** [comment]
Alright, tried a more complex password and nothing seems to be out-of-order. I'm new to Mattermost though, so someone else who is more familiar should prolly test it more thoroughly.

**Comment by kemenaran** [comment]
Yeah, that's definitely annoying :)

Unfortunately Yunohost doesn't have a facility to re-prompt the user again. However I just checked mattermost's documentation, and there is a way to relax the password constraints. I'll open an issue for this.

In the meantime, did you manage to install the app using a sufficiently complex password?

**Comment by kemenaran** [comment]
@win8linux thanks for testing!

In the meanwhile I also configured Mattermost to relax the password complexity rules. It now requires a 8-characters password, and that's it (no special chars or whatever).
