### ISSUE TITLE
mattermost deleted during the upgrade of ynh 2.7.9

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mattermost_ynh#90]
everything is in the title :/ 
i'm damned ....

**Comment by isAAAc** [comment]
there are the complete cli logs ;)
i wait a bit before trying a mattermost reinstall

https://paste.yunohost.org/uholihefuz.sql

**Comment by kemenaran** [comment]
Aw, crap. Sorry for this.

From the logs this is the same situation than before:

1. The upgrade begins
1. A backup of the current install is performed
1. The upgrade mostly succeeds, but fails to start the server at the end of the process
1. Yunohost sees a backup, and removes the app, because it is confident it can restore it from backup
1. but Yunohost fails to restore the backup, because it can't find the restore script

This is very curious. Well, at least if you have important data, there are stored in the backup (even if yunohost has troubles restoring it).

But there are still two mysteries here:

- Why does the upgrade fail?
- Why does Yunohost fail to restore the backup?

**Comment by kemenaran** [comment]
@isAAAc could you have a look again at the log files, to see if there would be the cause of why the server failed to start after the upgrade? I'm afraid some of the logs may have been deleted with the app, but we can have a look.

```
sudo journalctl -u mattermost
sudo journalctl -xn
tail /var/log/mattermost/mattermost.log
```

Thanks!

**Comment by isAAAc** [comment]
journalctl -u mattermost
> janv. 31 11:26:51 krashboyz systemd[1]: Starting Mattermost...
> janv. 31 11:26:51 krashboyz systemd[5429]: Failed at step USER spawning /var/www/mattermost/bin/platform: No such process
> janv. 31 11:26:51 krashboyz systemd[1]: mattermost.service: main process exited, code=exited, status=217/USER
> janv. 31 11:26:51 krashboyz systemd[5430]: Failed at step USER spawning /usr/bin/timeout: No such process
> janv. 31 11:26:51 krashboyz systemd[1]: mattermost.service: control process exited, code=exited status=217
> janv. 31 11:26:51 krashboyz systemd[1]: Failed to start Mattermost.
> janv. 31 11:26:51 krashboyz systemd[1]: Unit mattermost.service entered failed state.
> janv. 31 11:27:01 krashboyz systemd[1]: mattermost.service holdoff time over, scheduling restart.
> janv. 31 11:27:01 krashboyz systemd[1]: Stopping Mattermost...
> janv. 31 11:27:01 krashboyz systemd[1]: Starting Mattermost...
> janv. 31 11:27:01 krashboyz systemd[1]: mattermost.service: main process exited, code=exited, status=217/USER

journalctl -xn  gives nothing, to many stuff from statusnet in the log, and i rebooted so i think the interesting backlog is gone away :/

the /var/log gives nothing exept the stopping jobs during the upgrade

**Comment by kemenaran** [comment]
Interesting. The lines

```
systemd: Failed at step USER spawning /var/www/mattermost/bin/platform: No such process
…
systemd: Failed at step USER spawning /usr/bin/timeout: No such process
```

seem to indicate an invalid username in the systemd service configuration file.

And it turns out the user name is computed by Yunohost ; so an upgrade may have broken that.

I'll investigate further, try to perform the update myself, and tell you what I found. Thanks for the log!

**Comment by isAAAc** [comment]
Can i reinstall it or do you prefer i wait during your investigations ?

**Comment by kemenaran** [comment]
Sure, you can re-install: the application was removed anyway, so unfortunately there are no logs lefts or anything :)

**Comment by isAAAc** [comment]
yep , it's just the start of this service , so no real logs for now, but ppl are waiting for it, and each crash eat a bit of credibility each time :/

**Comment by isAAAc** [comment]
reinstall ok, 
waiting for your end of investigation :)

**Comment by kemenaran** [comment]
Thanks! I wrote some code today to work-around the backup being restored even if it is invalid – which should at least make upgrades safer. I'll push the code on monday; and from then we'll be able to better see what went wrong on your side.

**Comment by kemenaran** [comment]
I pushed a patch to keep the app even if the upgrade fails at some point (#92).

@isAAAc If it is possible for you, could you test this one? It should be safer for you – and for me, if something doesn't work as expected, we'll still have the app and log files to explore and know what went wrong (and you will still have your data).

For testing, the easiest way is to perform an upgrade using the CLI, to get the latest version of the app from Github:

```shell
sudo yunohost app upgrade mattermost --verbose --url https://github.com/YunoHost-Apps/mattermost_ynh
```

Thanks!

**Comment by isAAAc** [comment]
just done ;)

Do you want i try something like : 

> yunohost tools update && yunohost tools upgrade && yunohost app upgrade

or something else ?

**Comment by kemenaran** [comment]
@isAAAc great! How is it working? Did the upgrade went smoothly?

(Btw yunohost tools upgrade won't do anything, as I haven't propagated the Mattermost upgrade to the Yunohost apps community list yet)

**Comment by isAAAc** [comment]
yep everything works fine for now, i kept my datas, so i think we can say it was smoothly ;)

**Comment by kemenaran** [comment]
I tested again the upgrade from 8295da93cd36c66bf27e9b0082514f1dce255ba5 to the latest version, and it works as intended.

@isAAAc thanks a lot for your testing!
